DROP TYPE IF EXISTS team_type CASCADE;
CREATE TYPE team_type AS ENUM ('PERSONAL', 'TEAM');

DROP TYPE IF EXISTS membership_type CASCADE;
CREATE TYPE membership_type AS ENUM ('OWNER', 'ADMIN', 'MEMBER');

DROP TYPE IF EXISTS subscription_interval CASCADE;
CREATE TYPE subscription_interval AS ENUM ('MONTHLY', 'ANNUAL');

DROP TABLE IF EXISTS userinfo CASCADE;
CREATE TABLE userinfo (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  created TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS team CASCADE;
CREATE TABLE team (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  team_type TEAM_TYPE NOT NULL,
  created TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS subscription_plan CASCADE;
CREATE TABLE subscription_plan (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  team_id BIGINT REFERENCES team (id) ON DELETE CASCADE UNIQUE NOT NULL,

  interval SUBSCRIPTION_INTERVAL NOT NULL,
  subscription_price_in_usd_cents BIGINT NOT NULL,
  included_credits BIGINT NOT NULL,

  remaining_credits BIGINT NOT NULL,
  usd_cents_per_credit BIGINT NOT NULL,
  outstanding_balance_in_usd_cents BIGINT NOT NULL DEFAULT 0,
  subscription_active BOOLEAN NOT NULL DEFAULT FALSE,

  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP
);

DROP TABLE IF EXISTS team_membership CASCADE;
CREATE TABLE team_membership (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  team_id BIGINT REFERENCES team (id) ON DELETE CASCADE NOT NULL,
  user_id BIGINT REFERENCES userinfo (id) ON DELETE CASCADE NOT NULL,
  membership_type MEMBERSHIP_TYPE NOT NULL,
  created TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS project CASCADE;
CREATE TABLE project (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  team_id BIGINT REFERENCES team (id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  source_media TEXT NOT NULL,
  created TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS transformation CASCADE;
CREATE TABLE transformation (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  project_id BIGINT REFERENCES project (id) ON DELETE CASCADE NOT NULL,
  target_language TEXT NOT NULL,
  target_media TEXT NOT NULL,
  transcript jsonb,
  is_source BOOLEAN NOT NULL,
  status TEXT NOT NULL,
  progress DOUBLE PRECISION NOT NULL,
  created TIMESTAMP NOT NULL
);
