volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
  planetcast-gql-server:
    depends_on: [postgres]
